// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/lucky5-login/Polished.tsx": () => import("../components/mockups/lucky5-login/Polished.tsx"),
  "./components/mockups/lucky5-login/Refined.tsx": () => import("../components/mockups/lucky5-login/Refined.tsx")
};
